site_name: Liminal ORM
site_url: https://dynotx.github.io/liminal-orm/
nav:
  - Home: index.md
  - Getting Started:
      - getting-started/prerequisites.md
      - getting-started/installation.md
      - getting-started/setup.md
      - getting-started/first-migration.md
      - getting-started/downgrading.md
      - getting-started/tutorials.md
  - Reference:
      - reference/benchling-connection.md
      - reference/benchling-session.md
      - reference/dropdowns.md
      - reference/entity-schemas.md
      - reference/validators.md
      - reference/revision-file.md
      - reference/operations.md
  - Case Studies:
      - DynoTx Recommended SOP: case-studies/dynotx-recommended-sop.md
  - Contributing:
      - contributing.md
  - Future Direction:
      - future-direction.md
  - Release Notes:
      - release-notes.md
theme:
  name: material
  custom_dir: 'docs/theme'
  logo: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - header.autohide
    - navigation.footer
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  analytics:
    provider: google
    property: G-Z8YQTKP7B6
repo_url: https://github.com/dynotx/liminal-orm
repo_name: dynotx/liminal-orm
