from liminal.base.str_enum import StrEnum


class NameTemplatePartType(StrEnum):
    SEPARATOR = "SEPARATOR"
    TEXT = "TEXT"
    CREATION_YEAR = "CREATED_AT_YEAR"
    CREATION_DATE = "CREATED_AT_DATE"
    FIELD = "FIELD"
    REGISTRY_IDENTIFIER_NUMBER = "REGISTRY_IDENTIFIER_NUMBER"
    LINKED_BIOENTITY_REGISTRY_IDENTIFIER = "LINKED_BIOENTITY_REGISTRY_IDENTIFIER"
    PROJECT = "PROJECT"
    CHILD_ENTITY_LOT_NUMBER = "CHILD_ENTITY_LOT_NUMBER"
    COMPLEX_POLYMER_COMPONENT = "COMPLEX_POLYMER_COMPONENT"
